### PR TITLE
add no_std support

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by xfbs** [comment]
Hey, should I try rebasing this branch and seeing if I can get it to work?

**Comment by stevefan1999-personal** [comment]
@xfbs sure

**Comment by xfbs** [comment]
Hey, so I used your branch as a guide and pushed `no_std` support into `master`. Maybe you can take a look at it to make sure I did it right? I saw that you conditionally imported things from `core` or `std`, I figured we could just always import stuff from `core` or `alloc` and then only import the stuff from `std` that is std-only. Not sure if it makes sense this way. Happy to get some feedback :)

Cheers,
-Patrick

**Comment by stevefan1999-personal** [comment]
Much appreciated! In fact, I was thinking about whether or not to use the no-std-compat crate (https://crates.io/crates/no-std-compat) instead, but I though think it could cause more trouble in the long run...Now that you have cherrypicked my works I would say it's time to close it as resolved.

**Pull request closed without merging**
